### ISSUE TITLE
Support for v0.7/1.0

### ISSUE THREAD

**Issue by Wikunia** [lanl-ansi/Juniper.jl#104]
In development: https://github.com/lanl-ansi/Juniper.jl/tree/0.7
Currently unstable as sometimes test fail.

@ccoffrin The status update for solvers is only in MOI and has nothing to do with v0.18.3 of JuMP correct?

**Comment by ccoffrin** [comment]
Which "status update for solvers" are you referring to?

**Comment by Wikunia** [comment]
You mentioned a new system of status codes like `LocalInfeasible` instead of `Infeasible` but this probably only refers to this: http://www.juliaopt.org/MathOptInterface.jl/latest/apimanual.html#Common-status-situations-1

**Comment by ccoffrin** [comment]
That is correct, updating solver status values is part of MOI/JuMP v0.19 and is independent of Julia v0.7/JuMP v0.18.3.

**Comment by Wikunia** [comment]
Should work after https://github.com/JuliaLang/METADATA.jl/pull/18689 in v0.7 and v1. but seems slower then usual.
Also needs some todos:
- Changing `mu_init` of Ipopt doesn't work as before 
- Removed PowerModels test cases for now
- No support anymore for v0.6 but I think that is reasonable @ccoffrin

**Comment by ccoffrin** [comment]
Dropping support for v0.6 fine by me.

**Comment by Wikunia** [comment]
Can you @ccoffrin test this locally as well? Just running `] test Juniper` on v0.7 or v1.
Just want to be sure that it might be more a configuration thing on travis or something.

**Comment by ccoffrin** [comment]
Sure thing, just need to figure out how to checkout a branch on the new
package manager.

**Comment by Wikunia** [comment]
In the docu it says: `add Example#master` or you just clone the repository and then use `develop /src/to/Juniper` and checkout the branch manually there ;)

**Comment by ccoffrin** [comment]
CI is working on my mac laptop but it takes some time.  CI is more or less working as well.

I think we should drop `blend029` and any other tests that take more than a few seconds to run.

**Comment by ccoffrin** [comment]
Before merging this into master it would also be good to explore how much work it would be to support v0.6 as well.  Here is a working example, https://github.com/lanl-ansi/InfrastructureModels.jl/pull/15

**Comment by Wikunia** [comment]
Okay thanks. I'll have a look during the weekend. Yes the current error in CI has something to do with my debug logger which works locally but somehow something is wrong in CI. Anyway I'll have a look into whether I can figure that out and will drop blend as much as possible without reducing codecoverage and v0.6 support.

**Comment by Wikunia** [comment]
Very nice, thanks. Trying to add some test cases then and doing `Compat` stuff and then ready to bring Juniper back to life v0.3 :grinning:

**Comment by ccoffrin** [comment]
I will likely also be working on this today.  Be sure to commit your updates.

**Comment by Wikunia** [comment]
Sure. Don't work on it before my exam tmr that's for sure ;) 
Oh btw it's not easily possible anymore to set `mu_init` for Ipopt based on their new update. Miles mentioned that they are happy with a PR in Ipopt. What about running our test cases and compare it? See how important it actually is (run on v0.6) and also run it on 1.0 to see some speed comparison on the julia versions. If the `mu_init` isn't that important I think we can have 0.3 without it and integrate it either later or when we have MOI as it should be easier to set parameters then Miles said.

**Comment by Wikunia** [comment]
Waiting for https://github.com/JuliaOpt/Ipopt.jl/pull/147 then `mu_init` works again.
