### ISSUE TITLE
FP test for cvxnonsep_nsig20r_problem

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/Juniper.jl#105]
@Wikunia, can you double check this test, https://github.com/lanl-ansi/Juniper.jl/blob/437c184952a56cc9c572aa2f624697e1e42ad883/test/fpump.jl#L32

It looks like there is a bug in this test and it is just a copy of the test above.  Can you double check?

**Comment by Wikunia** [comment]
It's more or less a the same test just small changes in parameters but yes that shouldn't be the case. I suggest removing the test case and I'll check codecov later add try to add smaller tests for the more special cases.
