### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by Wikunia** [lanl-ansi/Juniper.jl#125]
@JuliaRegistrator register(branch=release-0.3)

**Comment by nkottary** [comment]
The issue is that we use julia's parser to parse `release-0.3` and it gets parsed as an expression `release - 0.3` instead of as a string.

**Comment by Wikunia** [comment]
For me it should be parsed as a string for the branching name, correct?

**Comment by nkottary** [comment]
Yes, that is the bug right now.

**Comment by Wikunia** [comment]
Okay thanks for investigating ;)

**Comment by nkottary** [comment]
I will push a fix and let you know when you can retry.

**Comment by nkottary** [comment]
It should work now. You need to string quote the branch argument as mentioned here: https://github.com/JuliaRegistries/Registrator.jl#how-to-use

**Comment by Wikunia** [comment]
@JuliaRegistrator register(branch="release-0.3")

**Comment by Wikunia** [comment]
Thanks @nkottary
