### ISSUE TITLE
Attributes and other features support

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/Juniper.jl#147]
@Wikunia @ccoffrin 

These are the attributes for which support can easily be added. 

- [x] MOI.Silent
- [x] MOI.TimeLimitSec
- [x] MOI.SolveTime
- [x] MOI.RawStatusString (this should be set to false)

The list of other features that are missing and could be added (if deemed suitable for Juniper) can be found in test/MOI_wrapper.jl in the exclude list. The unit tests for the strings in the exclude list can be found in https://github.com/JuliaOpt/MathOptInterface.jl/tree/master/src/Test/UnitTests

**Comment by Wikunia** [comment]
Why should `RawStatusString` be set to false? Can we not use `return string(model.inner.status)` ?

**Comment by Wikunia** [comment]
https://github.com/lanl-ansi/Juniper.jl/commit/cb9e0d35b305bf79306ebda413b0a756dee7fdbf 

I'm not sure whether we need all the `.supports` as it works without it for `RawStatusString`. Is `supports` only for setting things but not for getting? 

Added `RawStatusString` as just the `string(model.inner.status)` if this is wrong @kaarthiksundar I'll change it.

**Comment by Wikunia** [comment]
Solved by #148
