### ISSUE TITLE
Juniper + custom functions

### ISSUE THREAD

**Issue by kkmann** [lanl-ansi/Juniper.jl#164]
Hi,

I ran into trouble trying to get Juniper to work with custom functions:

```
using JuMP, Ipopt, Juniper

optimizer = Juniper.Optimizer
params = Dict{Symbol,Any}()
params[:nl_solver] = with_optimizer(Ipopt.Optimizer)

m = Model(, with_optimizer(optimizer, params))

@variable(m, x, start = 0.0)
@variable(m, y, start = 0.0)

f(x, y) = exp(x*y)
register(m, :f, 2, f; autodiff = true)

@NLobjective(m, Min, f(x, y))

optimize!(m)
```

throws a `KeyError: key :f not found`; code works fine when using Ipopt directly.

Best,

Kevin

**Comment by Wikunia** [comment]
I'm not on my computer atm and can only have a look in 20hours or something but hopefully this still works: https://github.com/lanl-ansi/Juniper.jl/issues/118#issuecomment-471338929

**Comment by Wikunia** [comment]
Does it work @kkmann ?

**Comment by kkmann** [comment]
Like a charm, and thanks for the quick reply! 👏 

Big fan of JuMP & friends, thanks for the work you put into it!
