### ISSUE TITLE
Initialize variable before optimization

### ISSUE THREAD

**Issue by hect1995** [lanl-ansi/Juniper.jl#167]
I have a MINLP problem where I want to optimize a set of variables x but I have an initial guess for them, can they be initialized to those values?

**Comment by Wikunia** [comment]
Should be possible with: http://www.juliaopt.org/JuMP.jl/stable/variables/#JuMP.set_start_value
Unfortunately this might not be added as an incumbent if discrete atm. Will only be given as a start value to the non linear solver. Can't test it atm. Should be set as an incumbent so leave this issue open and I'll fix it hopefully the next days (currently on vacation)

**Comment by hect1995** [comment]
What I have is a state vector : x = [x0,y0,x1,y1,...,xN,yN] where each <x_i,y_i> is one coordinate of a path I want to optimize and I have an initial non-optimized path at the beginning so I would like to initialize the whole x vector to that initial path, would it work for this case?
Sorry but I didn't understand totally your answer

**Comment by Wikunia** [comment]
`JuMP.set_start_value.(x_vars, x_guess)` should work where `x_vars` is just the JuMP variables and `x_guess` a vector of the start values. Hope that helps.

**Comment by Wikunia** [comment]
Should be check if this creates an incumbent.
