### ISSUE TITLE
Optimization crash ScalarAffineFunction

### ISSUE THREAD

**Issue by hect1995** [lanl-ansi/Juniper.jl#168]

**Comment by Wikunia** [comment]
Looks like I missed to implement interval constraints. You should be able to write the a <= x <= b as two constraints to get rid of the error.

**Comment by odow** [comment]
You should just make `supports_constraint` return false for intervals and it will be bridged

**Comment by odow** [comment]
Re-opening because this is a bug in Juniper.jl:
https://github.com/lanl-ansi/Juniper.jl/blob/f20d15939842230b92ae3d00d89b4989d61cde91/src/MOI_wrapper/constraints.jl#L20
This is not true for `Interval{Float64}` sets.
