### ISSUE TITLE
Document passing user-defined functions

### ISSUE THREAD

**Issue by odow** [lanl-ansi/Juniper.jl#173]
As raised on Discourse https://discourse.julialang.org/t/minlp-optimization-with-user-defined-objective-function/33627.

**Comment by Wikunia** [comment]
As mentioned by Miles in https://github.com/lanl-ansi/Juniper.jl/issues/118 we might want to get rid of working with expression graphs then this won't be a problem anymore.

**Comment by ccoffrin** [comment]
Given our current rate of progress on NLP improvements in JuMP, it seems suitable to have some documentation of the current hack in meantime.
