### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/Juniper.jl#181]
@JuliaRegistrator register() v0.6.0

**Comment by Wikunia** [comment]
@JuliaRegistrator register() v0.6.1

**Comment by Wikunia** [comment]
@JuliaRegistrator register() v0.6.2

**Comment by Wikunia** [comment]
@JuliaRegistrator register() 0.6.3

**Comment by Wikunia** [comment]
@JuliaRegistrator register() 0.6.4

**Comment by Wikunia** [comment]
@JuliaRegistrator register()

**Comment by Wikunia** [comment]
@JuliaRegistrator register()

**Comment by Wikunia** [comment]
@JuliaRegistrator register()

**Comment by odow** [comment]
We don't need an issue for this. You can comment on the commits.
