### ISSUE TITLE
ERROR: type DataType has no field optimizer_constructor

### ISSUE THREAD

**Issue by umbe0** [lanl-ansi/Juniper.jl#201]
I found this error running JuMP/Juniper without suppressing the outputs of both NL and MIL solvers.

This issue is opened as a reminder of [this topic](https://discourse.julialang.org/t/error-type-datatype-has-no-field-optimizer-constructor/47920) on the Julia discosure forum.

**Comment by ccoffrin** [comment]
Thanks for posting an issue @umbe0!

**Comment by blegat** [comment]
Closed by https://github.com/lanl-ansi/Juniper.jl/pull/202 ?
