### ISSUE TITLE
JuMP-free function API?

### ISSUE THREAD

**Issue by mohamed82008** [lanl-ansi/Juniper.jl#209]
Hi,

Thanks for this amazing package. I have been experimenting with it recently and it's been great! I wonder if there is any way to use Juniper away from JuMP? In particular, to avoid the splatting issue for user-defined functions. Thanks!

**Comment by Wikunia** [comment]
Hi,

thanks for using Juniper. Glad you like it.
There is only the lower level API MathOptInterface.jl but it normally makes things more user unfriendly.

What is your specific issue with user-defined functions? Just that you have to define them twice once for JuMP and once for Juniper?

**Comment by mohamed82008** [comment]
> What is your specific issue with user-defined functions? Just that you have to define them twice once for JuMP and once for Juniper?

Yes and I like to pass in my own hessian and gradient perhaps using a different AD package in Julia. Having to splat the input vector is also potentially problematic but so far the Julia compiler has been splatting like a champ.

**Comment by ccoffrin** [comment]
As I understand it there is no way to use Juniper with a different AD backend than JuMP's built in one.  The core point is how the NLPBlock is handled at the MOI level.

@odow, and I have been discussing how to generalize JuMP's AD backends but those features are not planned to come any time soon.

**Comment by mohamed82008** [comment]
I see. I imagine updating Juniper once JuMP's NLPBlock is refactored will also be a significant undertaking. Is refactoring NLPBlock something that can be broken into GSoC chunks?

**Comment by mohamed82008** [comment]
If it can be broken down into chunks, GSoC students or interns may be able to take a crack at it bit by bit. This may be faster than waiting for one or a few busy experts to do it all.

**Comment by Wikunia** [comment]
You might wanna checkout #207 as it doesn't require the register function part in Juniper anymore.

**Comment by mohamed82008** [comment]
Pretty cool!

**Comment by odow** [comment]
Can this be closed? JuMP is not a dependency anymore (just a test one).

**Comment by ccoffrin** [comment]
From what I can tell, yes this can be closed.

**Comment by mohamed82008** [comment]
I agree.
