### ISSUE TITLE
Clean up JuMP code in tests

### ISSUE THREAD

**Issue by odow** [lanl-ansi/Juniper.jl#224]
This smells like JuMP 0.18:
https://github.com/lanl-ansi/Juniper.jl/blob/df63a8d41b699be47d1eeecacef3ec2a6572c0e4/test/runtests.jl#L51-L70

**Comment by Wikunia** [comment]
Can you refer to what changed regarding this? I'm a bit out of the loop 😃 are there new ways to obtain the inner model now?

**Comment by odow** [comment]
`solve` is `optimize!`, followed by `termination_status`
`internalmodel` is `unsafe_backend`
`getsolvetime` is `solve_time`
`getobjgap` is `relative_gap`
