### ISSUE TITLE
Consider running fewer CI jobs

### ISSUE THREAD

**Issue by odow** [lanl-ansi/Juniper.jl#226]
Do we really need to test 6 combinations?
https://github.com/lanl-ansi/Juniper.jl/blob/df63a8d41b699be47d1eeecacef3ec2a6572c0e4/.github/workflows/ci.yml#L16-L22

Linux on the LTS and linux/Mac/windows on the latest point release should be okay.

I guess it's useful to test windows for the parallelism stuff, but there doesn't seem to be any OS-specific code (just the solver binaries), so I wonder if it's even worth testing on every platform. Has there ever been a case where things passed on linux but failed on Windows?

**Comment by ccoffrin** [comment]
My experience has been from time to time some trivially small models fail on one OS over another for some numerical issue.  This arrises in solver libraries (e.g. SCS is a common culprit) not the Julia code.  So we have made a habit of testing on all platforms.  That said, maybe the new JLL frameworks have mitigated this to some extent and we can be more restricted with what we test on.

**Comment by odow** [comment]
Flakey tests here: https://github.com/lanl-ansi/Juniper.jl/pull/220#issuecomment-971156208

**Comment by odow** [comment]
Closing because I think we need them all.
