### ISSUE TITLE
Disable log output to console/REPL?

### ISSUE THREAD

**Issue by agcmoser** [lanl-ansi/Juniper.jl#242]
Is there any way to disable all outputs to console/REPL during optimization when using Juniper?

**Comment by Wikunia** [comment]
Having `log_levels` set to an empty array should work.
https://lanl-ansi.github.io/Juniper.jl/stable/options/#log_levels::Vector{Symbol}-[[:Table,:Info,:Options]]

**Comment by agcmoser** [comment]
setting `log_levels` to `Symbol[]` indeed did the trick. thank @Wikunia for the fast response
