### ISSUE TITLE
solutions and functions from parent to child

### ISSUE THREAD

**Issue by GabrielPonte** [lanl-ansi/Juniper.jl#256]
Hi, I'm using Juniper with KNITRO as nl_solver, and I would like to ask two questions about Juniper, please. 

- Does the final solution from the parent become the initial starting point for the child in the nl_solver?

- I set f(x) and the gradient to my model using register(model, :my_dopt_func, n, dopt_f, dopt_∇f).  But I would like to change the function and the gradient inside the branch and bound. Is this possible? I have a better formulation, but I can't start from it because it has to satisfy some properties that are only satisfied inside the branch and bound.

Here is the code that I'm using
```
 nl_solver = () ->  MOI.Utilities.CachingOptimizer(
                            MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()),
                            KNITRO.Optimizer(
            OUTLEV = 0,
            CONVEX = 1,
            GRADOPT = 1,
            FEASTOL = 5e-6,
            OPTTOL = 5e-6,
            ALGORITHM = 1,
            HESSOPT = 3,
            BAR_FEASIBLE = 1,
        )
                        )
    model = Model(optimizer_with_attributes(Juniper.Optimizer, 
                "nl_solver"=>nl_solver,
                "branch_strategy" => :StrongPseudoCost,
            ))
    register(model, :my_dopt_func, n, dopt_f, dopt_∇f)
    @variable(model, x[1:n],Int);
    set_start_value.(x, vec(x_ls))
    @NLobjective(model, Max, my_dopt_func(x...))
    @constraint(model, sum(x) - s == 0);
    for i = (1:n)
        set_lower_bound(x[i],lb[i]);
        set_upper_bound(x[i],ub[i]);
    end
```
and I would like to say that in some branches, dopt_f and dopt_∇f are different.

Thank you!

**Comment by odow** [comment]
> I would like to say that in some branches, dopt_f and dopt_∇f are different.

I don't think this is possible. 

But can't you just write a single function that looks at the current values of `x` being passed in? Why do you need to change the entire function?

For example, you could write:
```Julia
function dopt_f(x...)
    if x[1] <= 0
        return sum(x[i]^2 for i in 2:length(x))
    else
        return sum(x[i] for i in 2:length(x))
    end
end
```

**Comment by GabrielPonte** [comment]
It's a really nice idea, thank you! 
I'm not doing this because I needed some information from the node, and I think this function doesn't accept other arguments as input. Still, I could try to use an auxiliary global variable and set it equal to the node information to help me decide it, right?

**Comment by odow** [comment]
You could try the global variable thing, but be wary. You're likely violating a lot of assumptions about how Juniper works, so there's no guarantee that you won't run into an error or incorrect solution.

**Comment by GabrielPonte** [comment]
Ok, thanks. 
And is there a way to set an initial solution to KNITRO inside Juniper?

**Comment by odow** [comment]
Juniper will Warmstart the continuous solves with solutions that it has available. I assume if you set one initially, it will also use that.

But as a general comment, Juniper is not designed so that you can mess with the solvers deep in the tree.

**Comment by GabrielPonte** [comment]
Understood, thank you so much!
