### ISSUE TITLE
Support `MOI.ScalarNonlinearFunction`

### ISSUE THREAD

**Issue by pulsipher** [lanl-ansi/Juniper.jl#262]
It would be great for Juniper to support the new MOI nonlinear interface. This will be required for InfiniteOpt to use it.

**Comment by odow** [comment]
Juniper doesn't need to? It depends on the sub solver for nonlinear stuff. Do you have an example where it currently doesn't work?

**Comment by pulsipher** [comment]
My mistake, I thought Juniper depended on the expression tree structure like Alpine. I tested it and you are right.
