### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/Juniper.jl#37]
README.md is getting sufficiently long that it might make sense to start using a documentation generator.  Especially for documenting the various solver parameters.  Documenter.jl is the way to go for Julia packages.

This repo provides a good minimalist example,
```
https://github.com/lanl-ansi/Katana.jl
```
Also note this line, which builds the docs as part of the CI, https://github.com/lanl-ansi/Katana.jl/blob/master/.travis.yml#L40.

**Comment by ccoffrin** [comment]
Docs look good to me.  You might want to see if there is an easy way to use doc strings and autodoc to get a similar result.  The advantage of doc strings is that they can be queried in the REPL and are easier to maintain.

Also I would recommend adding a link to the docs some place.  I usually make it the repo's website link in github.

**Comment by ccoffrin** [comment]
You can try putting a doc string on this, https://github.com/Wikunia/MINLPBnB/blob/523eb465b9e64f5eb8b55b4218a02cff6415f833/src/MINLPBnB.jl#L7

I am pretty sure that autodocs will pick it up.

**Comment by Wikunia** [comment]
Maybe I can get some insights from other programmers here: https://discourse.julialang.org/t/how-to-provide-the-perfect-documentation/6994 ;)

**Comment by ccoffrin** [comment]
Nice

**Comment by odow** [comment]
Closing because Juniper has docs: https://lanl-ansi.github.io/Juniper.jl/stable/

There's always room for improvement, but I don't think we need an issue.
