### ISSUE TITLE
Feasiblity Pump without any Linear Constraints

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/Juniper.jl#77]
If you run the model example from the readme with a MIP solver, so that FP will run, the solver crashes with this error,
```
ERROR: UndefVarError: mip_obj not defined
Stacktrace:
 [1] fpump(::Juniper.JuniperModel) at .julia/v0.6/Juniper/src/fpump.jl:389
...
```

The issue seems to be that no linear constraints are defined in the model.

**Comment by Wikunia** [comment]
True. Is `NaN` a valid output? This is just for the table log. Otherwise it's not needed. Also `-` might be reasonable way to display it.

**Comment by ccoffrin** [comment]
probably `-` is better.  Seeing NaN in solver output usually means something has gone awry.
